### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by NexSqaud** [a-a-maly/kumir2#7]
Console output: https://pastebin.com/WLKPuF9q
CMakeOutput.log: https://pastebin.com/CrLVHJaV
Qt version: 5.14.2
QTDIR: E:\Qt\5.14.2\msvc2017_64
QMAKESPEC: E:\Qt\5.14.2\msvc2017_64\mkspecs\winrt-arm64-msvc2019

**Comment by a-a-maly** [comment]
Thanks for testing Kumir2!
It needs working git program and python3 to build. 
git is needed mostly to get (and embed) version information, python3 - for auxillary service functions, as well as for runtime generating and building subprojects, even generating source files for them. The last thing is a legacy part I hate most, but still have no time to get rid of.
Possible build scenarios you can find in .gitlab.yml file in the topmost directory of the project.

**Comment by NexSqaud** [comment]
I have git installed in C:\Program Files\Git and python 3.8.1.
I have tried:
- build:win32: from .gitlab-cli.yml [Console output](https://pastebin.com/rRn765Jz) [CMakeError.log](https://pastebin.com/xyuBWnzi) [CMakeOutput.log](https://pastebin.com/TFHTNq12)
- run x64 Native Build Tools and cmake with parameters from .gitlab-cli.yml [Console output](https://pastebin.com/RA0KTnsw) [CMakeOutput.log](https://pastebin.com/4nchU00h)
- change QMAKESPEC to winrt-x64-msvc2017 - same

**Comment by NexSqaud** [comment]
#5 fix problem
